apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "pretix.fullname" . | trunc 58 }}-cron
  labels:
    {{- include "pretix.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
            restartPolicy: OnFailure
            volumes:
            - name: pretix-data
              persistentVolumeClaim:
                claimName: {{ include "pretix.fullname" .  | trunc 58 }}-data
            {{- if .Values.podSecurityContext }}
            securityContext:
              {{- toYaml .Values.podSecurityContext | nindent 12 }}
            {{- end }}
            imagePullSecrets:
            {{- if .Values.image.pullSecrets }}
            {{- range .Values.image.pullSecrets }}
              - name: {{ . }}
            {{- end }}
            {{- end }}
            containers:
            - name: pretix-cron
              image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["pretix"]
              args: ["cron"]
              volumeMounts:
              - name: pretix-data
                mountPath: /data
              env:
              {{- range $key, $value := .Values.env }}
              - name: {{ $key }}
                value: {{ $value | quote }}
              {{- end }}
              {{if .Values.extraEnv }}
              {{ .Values.extraEnv | toYaml | nindent 14 }}
              {{- end}}
