apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pretix.fullname" . | trunc 59 }}-web
  labels:
    app: {{ include "pretix.fullname" . }}
    service: web
    {{- include "pretix.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.pretixWeb }}
  selector:
    matchLabels:
      app: {{ include "pretix.fullname" . }}
      service: web
  template:
    metadata:
      labels:
        app: {{ include "pretix.fullname" . }}
        service: web
    spec:
      imagePullSecrets:
      {{- if .Values.image.pullSecrets }}
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: pretix-web
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["pretix"]
        args: ["web"]
        env:
        - name: AUTOMIGRATE # Migrations are handled by helm hooks in pretix-migrate.yaml
          value: "skip"
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{if .Values.extraEnv }}
        {{ .Values.extraEnv | toYaml | nindent 8}}
        {{- end}}
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pretix-data
          mountPath: /data
      volumes:
      - name: pretix-data
        persistentVolumeClaim:
          claimName: {{ include "pretix.fullname" .  | trunc 58 }}-data
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
