apiVersion: v1
kind: Service
metadata:
  name: {{ include "pretix.fullname" . }}-web
  labels:
    {{- include "pretix.labels" . | nindent 4 }}
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
  selector:
    app: {{ include "pretix.fullname" . }}
    service: web
