apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pretix.fullname" .  | trunc 55 }}-migrate
  labels:
    {{- include "pretix.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: pretix-data
        persistentVolumeClaim:
          claimName: {{ include "pretix.fullname" .  | trunc 58 }}-data
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      imagePullSecrets:
      {{- if .Values.image.pullSecrets }}
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: pretix-migrate
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["pretix"]
        args: ["migrate"]
        volumeMounts:
        - name: pretix-data
          mountPath: /data
        env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{if .Values.extraEnv }}
          {{ .Values.extraEnv | toYaml | nindent 10 }}
          {{- end}}
