apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "pretix.fullname" . }}-cron
  labels:
    {{- include "pretix.labels" . | nindent 4 }}
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
            restartPolicy: OnFailure
            containers:
            - name: pretix-cron
              image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["pretix"]
              args: ["cron"]
              env:
              {{- range $key, $value := .Values.env }}
              - name: {{ $key }}
                value: {{ $value | quote }}
              {{- end }}