apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pretix.fullname" . | trunc 58 }}-data
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}