name: pretix
description: Reinventing ticket presales, one ticket at a time.
type: application
version: 2025.3.1
appVersion: 2025.3.0
apiVersion: v2
keywords:
  - event-tickets
dependencies:
  - name: postgresql
    version: "15.1.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "20.13.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
sources:
  - https://github.com/pretix/pretix
  - https://github.com/techwolf12/charts
  - https://hub.docker.com/r/pretix/standalone
icon: https://raw.githubusercontent.com/techwolf12/charts/main/pretix-helm/icon.png
maintainers:
  - name: Chrsitiaan de Die le Clercq
    email: contact@techwolf12.nl
    url: https://techwolf12.nl/
